import { writable } from 'svelte/store';
import type { PhotosDataWithContainerType as PhotosDataTypes } from '$lib/utils/types/Beverage/PhotosData';
import type { Ingredient as IngredientType } from '$lib/utils/types/Ingredient';
import type { Institution as InstitutionType } from '$lib/utils/types/Institution';
import type { Place as PlaceType } from '$lib/utils/types/Place';
import type { Style as StyleType } from '$lib/utils/types/Style';
import type { LabelFormValues } from '$lib/dashboard/beverage/label/LabelFormValues';
import type { ProducerFormValues } from '$lib/dashboard/beverage/producer/ProducerFormValues';
import type { EditorialFormValues } from '$lib/dashboard/beverage/editorial/EditorialFormValues';
import type { StylesStats as StylesStatsTypes } from '$lib/utils/types/stats/Styles';
import { initialValues as initialLabelValues } from '$lib/dashboard/beverage/label/initialValues';
import { initialValues as initialProducerValues } from '$lib/dashboard/beverage/producer/initialValues';
import { initialValues as initialEditorialValues } from '$lib/dashboard/beverage/editorial/initialValues';

export const beveragePhotosStore = writable<PhotosDataTypes | null>(null);
export const editorialStore = writable<EditorialFormValues>(initialEditorialValues);
export const ingredientsStore = writable<IngredientType[]>([]);
export const institutionStore = writable<InstitutionType[]>([]);
export const labelStore = writable<LabelFormValues>(initialLabelValues);
export const page = writable<'label' | 'producer' | 'editorial'>('label');
export const placeStore = writable<PlaceType[]>([]);
export const producerStore = writable<ProducerFormValues>(initialProducerValues);
export const statsStyle = writable<StylesStatsTypes[]>([]);
export const styleStore = writable<StyleType[]>([]);
